CREATE TABLE [dbo].[Car]
(
	[Id] UNIQUEIDENTIFIER NOT NULL,
	[PublicKey] NVARCHAR(255) NOT NULL,
	[Color] VARCHAR(50) NOT NULL,
	[Ts] ROWVERSION NOT NULL,
	CONSTRAINT PK_Car PRIMARY KEY CLUSTERED (Id)
)