CREATE TABLE [dbo].[Wheel]
(
	[Id] UNIQUEIDENTIFIER NOT NULL,
	[CarId] UNIQUEIDENTIFIER NOT NULL,
	CONSTRAINT PK_Wheel PRIMARY KEY CLUSTERED (Id),
	CONSTRAINT FK_Wheel_Car FOREIGN KEY ([CarId]) REFERENCES [Car] ([Id])
)